[package]
name = "bones"
version = "0.0.1"
authors = ["lance <lza_menace@protonmail.com>"]
edition = "2018"

[dependencies]
irc = "0.13.6"
openssl = { version = "0.10", features = ["vendored"] }
postgres = "0.17.2"
