[package]
name = "bones"
version = "0.0.1"
authors = ["lance <lza_menace@protonmail.com>"]
edition = "2018"

[dependencies]
irc = "0.13.6"
http = "0.2"
openssl = { version = "0.10", features = ["vendored"] }
tokio-postgres = "0.5.3"
tokio = { version = "0.2.13", features = ["full"] }
