owners = ["yourmain"]
nickname = "botname"
server = "chat.freenode.net"
port = 6697
use_ssl = true
channels = ["#random"]
user_info = "I'm a test bot. Leave me be."

[options]
db_host = "localhost"
db_user = "postgres"
db_pass = "postgres"
db_name = "communitybot"
