version: '3'
services:
  db:
    image: postgres:9.6.15-alpine
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: communitybot
    volumes:
      - ./data/postgresql:/var/lib/postgresql/data
